# Generated by Django migration for ChatMessage model

import uuid
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_chatwithcontext_id'),
    ]

    operations = [
        # First create ChatMessage model
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(
                    choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')],
                    help_text='Role of the message sender',
                    max_length=20
                )),
                ('content_type', models.CharField(
                    choices=[
                        ('text', 'Text'),
                        ('thought', 'Thought'),
                        ('sources', 'Sources'),
                        ('tool_use', 'Tool Use'),
                        ('tool_result', 'Tool Result'),
                        ('id', 'ID'),
                        ('file_ids', 'File IDs'),
                    ],
                    default='text',
                    help_text='Type of content',
                    max_length=50
                )),
                ('content', models.TextField(help_text='Message content')),
                ('context_collected', models.BooleanField(default=False, help_text='Whether context was collected for this message')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context data (screen content, etc.)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (tool_id, function_name, etc.)', null=True)),
                ('step_number', models.IntegerField(blank=True, help_text='Step number in multi-step conversation (for assistant messages)', null=True)),
                ('modality_type', models.CharField(blank=True, help_text='Modality type if this message triggered a modality (for assistant messages)', max_length=100, null=True)),
                ('is_final', models.BooleanField(default=False, help_text='Whether this is the final message in a conversation turn')),
                ('questions_asked', models.IntegerField(default=0, help_text='Number of questions asked in this message (for assistant messages)')),
                ('chat', models.ForeignKey(
                    help_text='Chat this message belongs to',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='messages',
                    to='db.chatwithcontext'
                )),
                ('root_message', models.ForeignKey(
                    blank=True,
                    help_text='Reference to the root message of this conversation chain',
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='chain_messages',
                    to='db.chatmessage'
                )),
                ('parent_message', models.ForeignKey(
                    blank=True,
                    help_text='Previous message in the chain',
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='child_messages',
                    to='db.chatmessage'
                )),
                ('child_message', models.OneToOneField(
                    blank=True,
                    help_text='Next message in the chain',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='parent',
                    to='db.chatmessage'
                )),
            ],
            options={
                'verbose_name': 'chat message',
                'verbose_name_plural': 'chat messages',
                'ordering': ['created_at'],
            },
        ),
        # Then add root_message field to ChatWithContext
        migrations.AddField(
            model_name='chatwithcontext',
            name='root_message',
            field=models.ForeignKey(
                blank=True,
                help_text='Root message of the conversation chain',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='chat_root',
                to='db.chatmessage'
            ),
        ),
        # Remove the old chat_history field
        migrations.RemoveField(
            model_name='chatwithcontext',
            name='chat_history',
        ),
        # Add indexes
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'created_at'], name='db_chatmess_chat_id_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['root_message', 'created_at'], name='db_chatmess_root_me_created_idx'),
        ),
    ]
