# Generated by Django migration for File model and file_ids field

import uuid
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_add_chatmessage_model'),
    ]

    operations = [
        # Create File model
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(help_text='Original filename', max_length=512)),
                ('content_type', models.CharField(help_text='MIME type of the file', max_length=255)),
                ('size', models.IntegerField(help_text='File size in bytes')),
                ('file_key', models.CharField(help_text='S3 key or local file path', max_length=512)),
                ('entity_id', models.CharField(blank=True, help_text='Related entity ID (e.g., chat_id)', max_length=255, null=True)),
                ('entity', models.CharField(blank=True, help_text="Related entity type (e.g., 'chat')", max_length=255, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='Last time file was accessed', null=True)),
                ('width', models.IntegerField(blank=True, help_text='Image width (if image)', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Image height (if image)', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
            },
        ),
        # Add file_ids field to ChatMessage
        migrations.AddField(
            model_name='chatmessage',
            name='file_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of file IDs (UUIDs) attached to this message', null=True),
        ),
        # Add indexes for File
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['entity', 'entity_id'], name='db_file_entity_entity_id_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['status', 'created_at'], name='db_file_status_created_idx'),
        ),
    ]

