# Generated by Django 5.1.13 on 2025-11-02 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_add_file_model_and_file_ids'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='db_chatmess_chat_id_6bbb50_idx',
            old_name='db_chatmess_chat_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='db_chatmess_root_me_8123da_idx',
            old_name='db_chatmess_root_me_created_idx',
        ),
        migrations.RenameIndex(
            model_name='file',
            new_name='db_file_entity_62416d_idx',
            old_name='db_file_entity_entity_id_idx',
        ),
        migrations.RenameIndex(
            model_name='file',
            new_name='db_file_status_4472a2_idx',
            old_name='db_file_status_created_idx',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
